### ISSUE TITLE
node's (x,y) not being respected

### ISSUE THREAD

**Issue by lobotomisador** [vivien000/st-cytoscape#1]
Hi @vivien000 awesome work on this component. I'm currently using it to 'plot' frames which are rectangular grids, the input elements supplied to `cytoscape` is the following
```
[{'data': {'id': 0, 'label': '0'},
  'classes': 'fixed',
  'position': {'x': 0.0, 'y': 0.0}},
 {'data': {'id': 1, 'label': '1'},
  'classes': 'fixed',
  'position': {'x': 100.0, 'y': 0.0}},
 {'data': {'id': 2, 'label': '2'},
  'classes': 'free',
  'position': {'x': 0.0, 'y': 100.0}},
 {'data': {'id': 3, 'label': '3'},
  'classes': 'free',
  'position': {'x': 100.0, 'y': 100.0}},
 {'data': {'source': 0, 'target': 2, 'type': 'column', 'tag': 0, 'r': 20.0}},
 {'data': {'source': 1, 'target': 3, 'type': 'column', 'tag': 1, 'r': 20.0}},
 {'data': {'source': 2, 'target': 3, 'type': 'beam', 'tag': 2, 'r': 20.0}}]
```
I would expect a rectangular shape like this 
2__3
|      |
0    1
However, I get random positions of nodes.
![image](https://user-images.githubusercontent.com/85521045/169672636-78bf21f7-3a0f-4ecf-8c68-d2b5254c639f.png)
![image](https://user-images.githubusercontent.com/85521045/169672641-282c4734-93e1-4b3f-80f8-5d7b8b87ed57.png)

Let me know if this is a missing feature and I will make a PR for it.

**Comment by vivien000** [comment]
Hi @lobotomisador . What did you specify for the layout parameter (cf. README)? The x/y values are just the initial coordinates that are potentially modified by the layout algorithm. The default layout algorithm (fcose) always changes them

**Comment by lobotomisador** [comment]
@vivien000 That was the issue. I was using the default layout algorithm, when I changed the layout to 


```
layout = {"name": "preset"}
```

it worked.

Closing the issue.

**Comment by lobotomisador** [comment]
Closed due to using incorrect layout.
